services:
  - type: web
    name: eshop-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: PRODUCTION
      - key: PORT
        value: 10000
      - key: DB_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRES
        value: 7d
      - key: ACTIVATION_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_MAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
